bump & compileOnly simple-xml
thegrizzlylabs/sardine-android pull request #74
Opened 2024-02-13 14:23 UTC by storytellerF

update jdk17

replace deprecated

fix reals artifact upload

2024-02-13 14:38 UTC, guillaume-tgl reviewed
Great work, thanks! But it seems like CI is failing. Can you have a look at it?

2024-02-13 14:38 UTC, guillaume-tgl commented on build.gradle
> +    compileOnly('org.simpleframework:simple-xml:2.7.1') {
Is this correct? the SimpleXml library is also needed at runtime, no?

2024-02-14 17:05 UTC, merged

2026-05-21 18:18 UTC, dayanmasiha-hub commented on build.gradle
> +    compileOnly('org.simpleframework:simple-xml:2.7.1') {
lhow can uset xml Files 
من یک کاربر اندروید روت شده (Samsung A32) با مشخصات زیر هستم:
OS: Android 13 | Build: A325FXXS9DXE3 | Root: Magisk v30.7 | Kernel: 4.14.186

محدودیت‌های من:
۱. اینترنت ملی دارم (دسترسی به سرویس‌های گوگل و اکثر دامنه‌ها مسدود است).
۲. دسترسی به جیمیل برای احراز هویت ندارم (لاگین در سایت‌ها مثل گیت‌هاب غیرممکن است).
۳. کامپیوتر ندارم (فقط گوشی و کابل OTG/فلش).
۴. به گیت‌هاب (به صورت عمومی و بدون لاگین) دسترسی دارم.
هدف من:
مدیریت دیوایس، دور زدن تحریم‌ها، اجرای اسکریپت‌ها در Termux، و بهینه‌سازی بدون نیاز به آنروت کردن.
دستورالعمل برای شما:
پاسخ‌ها باید کاملاً فنی، ساختاریافته و با رویکرد برنامه‌نویسی/مهندسی باشد.
راهکارهایی پیشنهاد دهید که صرفاً متکی به فایل‌های نصبی (APK)، اسکریپت‌های ترموکس یا تغییرات در سطح Root/Magisk باشند.
از معرفی سایت‌هایی که برای دانلود فایل نیاز به لاگین یا عبور از کپچاهای سخت گوگل دارند خودداری کنید (مگر اینکه راهی برای دور زدن مستقیم وجود داشته باشد).
اگر می‌خواهید ابزاری معرفی کنید، مستقیماً لینکِ Direct Download (از گیت‌هاب یا مخازن باز) بدهید.
به من یاد بده چطور محدودیت‌های شبکه را در لایه iptables یا proxychains در ترموکس کنترل کنم تا دیگر برای آپدیت یا نصب پکیج‌ها نیازی به سرویس‌های گوگل نداشته باشم."

2026-05-21 18:38 UTC, dayanmasiha-hub approved these changes
d0af7ae8e7ee0654a763c4c6f638a5e98b1782e9

2026-05-21 18:38 UTC, dayanmasiha-hub requested changes
d0af7ae8e7ee0654a763c4c6f638a5e98b1782e9